services:
  postgres:
    image: postgres:16-alpine
    container_name: engine-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_OS_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: engine-redis
    ports:
      - "${REDIS_OS_PORT}:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: engine-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  pgdata:
